sudo: required
services:
  - docker

before_install:
  - docker build -t react-app-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-app-test npm run test -- --coverage

after_success:
  - docker build -t ccheatham/complex-client ./client
  - docker build -t ccheatham/complex-server ./server
  - docker build -t ccheatham/complex-nginx ./nginx
  - docker build -t ccheatham/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ccheatham/complex-client
  - docker push ccheatham/complex-server
  - docker push ccheatham/complex-nginx
  - docker push ccheatham/complex-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "react-app"
#   env: "ReactApp-env"
#   bucket_name: "elasticbeanstalk-us-east-1-144468571614"
#   bucket_path: "react-app"
#   on: 
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
